---
- hosts: localhost
  connection: local

  tasks:
  - name: Update homebrew
    community.general.homebrew:
      update_homebrew: yes

  - name: Upgrade all packages
    community.general.homebrew:
      upgrade_all: yes
